last-up #10

diff --git a/astra/raid-configuration b/astra/raid-configuration
--- a/astra/raid-configuration
+++ b/astra/raid-configuration
@@ -18,10 +18,10 @@ log() {
 }
 
 service_registry() {
-    log -e "\033[1;37m[i] Регистрация сервиса для постреализации...\033[0m"
+    log "\033[1;37m[i] Регистрация сервиса для постреализации...\033[0m"
 
     if [ -f "$SERVICE_PATH" ]; then
-        log -e "\033[1;37m[i] Сервис уже зарегистрирован.\033[0m"
+        log "\033[1;37m[i] Сервис уже зарегистрирован.\033[0m"
         return
     fi
     cat <<EOF > "$SERVICE_PATH"
@@ -47,14 +47,14 @@ EOF
     systemctl daemon-reload
     systemctl enable "$SERVICE_NAME"
 
-    log -e "\033[1;32m✅ Сервис успешно зарегистрирован.\033[0m"
+    log "\033[1;32m✅ Сервис успешно зарегистрирован.\033[0m"
 }
 
 service_unregistry() {
-    log -e "\033[1;37m[i] Удаление сервиса для постреализации...\033[0m"
+    log "\033[1;37m[i] Удаление сервиса для постреализации...\033[0m"
 
     if [ ! -f "$SERVICE_PATH" ]; then
-        log -e "\033[1;37m[i] Сервис не зарегистрирован.\033[0m"
+        log "\033[1;37m[i] Сервис не зарегистрирован.\033[0m"
         return
     fi
 
@@ -62,7 +62,7 @@ service_unregistry() {
     rm -f "$SERVICE_PATH"
     rm -f /usr/local/bin/raid-configuration
 
-    log -e "\033[1;32m✅ Сервис успешно удален.\033[0m"
+    log "\033[1;32m✅ Сервис успешно удален.\033[0m"
 }
 
 get_parent_disk_from_lvm() {
@@ -184,16 +184,16 @@ step_one() {
     fi
 
     lvm_part="${lvm_parts[0]}"
-    echo -e "\033[1;37mНайден LVM: $lvm_part\033[0m"
+    echo -e "\033[1;37m[i] Найден LVM: $lvm_part\033[0m"
     parent_disk=$(get_parent_disk_from_lvm "$lvm_part")
-    echo -e "\033[1;37mНайден основной диск: $parent_disk\033[0m"
+    echo -e "\033[1;37m[i] Найден основной диск: $parent_disk\033[0m"
     
     mapfile -t parent_parts < <(lsblk -ln -o PATH,TYPE "$parent_disk" | awk '$2 == "part" {print $1}')
     for part in "${parent_parts[@]}"; do
         echo "  - $part"
     done
 
-    echo -e "\033[1;37mПоиск диска с аналогичным размером...\033[0m"
+    echo -e "\033[1;37m[i] Поиск диска с аналогичным размером...\033[0m"
 
     # Получаем имя диска без /dev/
     base_disk=$(basename "$parent_disk")
@@ -215,16 +215,16 @@ step_one() {
         exit 1
     fi
 
-    echo -e "\033[1;37mТаблица разделов будет мигрирована с $parent_disk на $second_disk\033[0m"
+    echo -e "\033[1;37m[i] Таблица разделов будет мигрирована с $parent_disk на $second_disk\033[0m"
     default="y"
-    read -t 5 -p "Подтвердите действия (y/N): " -n 1 -r
+    read -t 5 -p "[r] Подтвердите действия (y/N): " -n 1 -r
     echo ""
     REPLY=${REPLY:-$default}  # если REPLY пустой, подставить значение по умолчанию
 
     if [[ $REPLY =~ ^[Yy]$ ]]; then
-        echo "Выполняем..."
+        echo -e "\033[1;32m✅ Выполняем..."
     else
-        echo "Отменено."
+        echo -e "\033[1;31m❌ Отменено."
         exit 1
     fi
 
@@ -237,7 +237,7 @@ step_one() {
 
     VG_NAME="VG$MAIN_LVM_VGID"
 
-    echo -e "\033[1;37mПоиск физического раздела, где размещён VG $VG_NAME...\033[0m"
+    echo -e "\033[1;37m[i] Поиск физического раздела, где размещён VG $MAIN_LVM_VGID...\033[0m"
     pv_partition=$(pvs --noheadings -o pv_name,vg_name | awk -v vg="$VG_NAME" '$2 == vg {print $1}')
 
     if [[ -z "$pv_partition" ]]; then
@@ -249,9 +249,9 @@ step_one() {
 
     # Сохраняем номер раздела, например: sda3 → 3
     part_number=$(echo "$pv_partition" | grep -oP '\d+$')
-    echo -e "\033[1;37mНомер раздела: $part_number\033[0m"
+    echo -e "\033[1;37m[i] Номер раздела: $part_number\033[0m"
 
-    echo -e "\033[1;37mСоздание деградированного массива RAID первого уровня (зеркало)...\033[0m"
+    echo -e "\033[1;37m[i] Создание деградированного массива RAID первого уровня (зеркало)...\033[0m"
 
     if mdadm --create --force --metadata=1.2 /dev/md0 -l 1 -n 2 missing ${second_disk}${part_number} >/dev/null 2>&1; then
         echo -e "\033[1;32m✅ Деградированный массив RAID успешно создан.\033[0m"
@@ -260,7 +260,7 @@ step_one() {
         exit 1
     fi
 
-    echo -e "\033[1;37mСоздание физического тома в LVM на /dev/md0...\033[0m"
+    echo -e "\033[1;37m[i] Создание физического тома в LVM на /dev/md0...\033[0m"
 
     if pvcreate /dev/md0 >/dev/null 2>&1; then
         echo -e "\033[1;32m✅ Физический том успешно создан в LVM.\033[0m"
@@ -269,11 +269,11 @@ step_one() {
         exit 1
     fi
 
-    echo -e "\033[1;37mДобавляем том в состав группы томов...\033[0m"
+    echo -e "\033[1;37m[i] Добавляем том в состав группы томов...\033[0m"
 
     vgextend VG$MAIN_LVM_VGID /dev/md0
 
-    echo -e "\033[1;37mПеремещаем данные из существующего тома с корневой файловой системой на ранее созданный том...\033[0m"
+    echo -e "\033[1;37m[i] Перемещаем данные из существующего тома с корневой файловой системой на ранее созданный том...\033[0m"
 
     if pvmove ${parent_disk}${part_number} /dev/md0 >/dev/null 2>&1; then
         echo -e "\033[1;32m✅ Данные успешно перемещены.\033[0m"
@@ -282,7 +282,7 @@ step_one() {
         exit 1
     fi
 
-    echo -e "\033[1;37mИсключаем ${parent_disk}${part_number}  из группы томов...\033[0m"
+    echo -e "\033[1;37m[i] Исключаем ${parent_disk}${part_number}  из группы томов...\033[0m"
 
     if vgreduce VG$MAIN_LVM_VGID ${parent_disk}${part_number}  >/dev/null 2>&1; then
         echo -e "\033[1;32m✅ ${parent_disk}${part_number}  успешно исключен из группы томов.\033[0m"
@@ -291,7 +291,7 @@ step_one() {
         exit 1
     fi
 
-    echo -e "\033[1;37mУдаление тома ${parent_disk}${part_number}...\033[0m"
+    echo -e "\033[1;37m[i] Удаление тома ${parent_disk}${part_number}...\033[0m"
 
     if pvremove ${parent_disk}${part_number} >/dev/null 2>&1; then
         echo -e "\033[1;32m✅ Том ${parent_disk}${part_number} успешно удален.\033[0m"
@@ -300,7 +300,7 @@ step_one() {
         exit 1
     fi
 
-    echo -e "\033[1;37mПрименение системных изменений...\033[0m"
+    echo -e "\033[1;37m[i] Применение системных изменений...\033[0m"
 
     if update-initramfs -uk all >/dev/null 2>&1; then
         if update-grub >/dev/null 2>&1; then
@@ -314,20 +314,20 @@ step_one() {
         exit 1
     fi
 
-    echo -e "\033[1;37mДоперезагрузочный этап завершен.\033[0m"
+    echo -e "\033[1;37m[i] Доперезагрузочный этап завершен.\033[0m"
 
-    echo -e "\033[1;37mСоздание конфигурационного файла для послезагрузочного этапа...\033[0m"
+    echo -e "\033[1;37m[i] Создание конфигурационного файла для послезагрузочного этапа...\033[0m"
 
     echo "PARENT_DISK=$parent_disk" > "$CONFIG_FILE"
     echo "SECOND_DISK=$second_disk" >> "$CONFIG_FILE"
     echo "PART_NUMBER=$part_number" >> "$CONFIG_FILE"
 
-    echo -e "\033[1;37mКомпьютер будет автоматически перезагружен в течении 30 секунд.\033[0m"
+    echo -e "\033[1;37m[i] Компьютер будет автоматически перезагружен в течении 30 секунд.\033[0m"
 
-    echo -e "\033[1;37mВнимание! После перезагрузки, скрипт автоматически активирует второй этап через автозагрузку, но...\033[0m"
+    echo -e "\033[1;37m[i] Внимание! После перезагрузки, скрипт автоматически активирует второй этап через автозагрузку, но...\033[0m"
     echo -e "\033[1;37m...действия скрипта будут выполняться в фоне из-за невозможности запуска сессии fly-dm от имени суперпользователя...\033[0m"
     echo -e "\033[1;37m..поэтому для отслеживания действий скрипта после перезагрузки и конец его действий, можно посмотреть следующий лог файл:\033[0m"
-    echo -e "\033[1;37m...$LOG_FILE\033[0m"]
+    echo -e "\033[1;37m...$LOG_FILE\033[0m"
 
     service_registry
 
@@ -336,11 +336,11 @@ step_one() {
 }
 
 step_two() {
-    log -e "\033[1;32m✅ Послезагрузочный этап запущен. Скрипт активен.\033[0m"
+    log "\033[1;32m✅ Послезагрузочный этап запущен. Скрипт активен.\033[0m"
 
-    log -e "\033[1;37mПослезагрузочный этап...\033[0m"
+    log "\033[1;37m[i] Послезагрузочный этап...\033[0m"
 
-    log -e "\033[1;37mПроверка деградированного массива RAID...\033[0m"
+    log "\033[1;37m[i] Проверка деградированного массива RAID...\033[0m"
 
     mdadm_output=$(mdadm --detail /dev/md0 2>/dev/null)
 
@@ -349,19 +349,19 @@ step_two() {
     working=$(echo "$mdadm_output" | awk -F': ' '/Working Devices/ {print $2}' | tr -d ' ')
     failed=$(echo "$mdadm_output" | awk -F': ' '/Failed Devices/ {print $2}' | tr -d ' ')
 
-    log -e "\033[1;37mСостояние массива: $state\033[0m"
-    log -e "\033[1;37mАктивных устройств: $active, Рабочих: $working, Неисправных: $failed\033[0m"
+    log "\033[1;37m[i] Состояние массива: $state\033[0m"
+    log "\033[1;37m[i] Активных устройств: $active, Рабочих: $working, Неисправных: $failed\033[0m"
 
     # Условия: деградирован и одно устройство
     if [[ "$state" == *degraded* && "$active" == "1" && "$working" == "1" && "$failed" == "0" ]]; then
-        log -e "\033[1;32m✅ Массив действительно деградирован и содержит одно устройство — всё верно.\033[0m"
+        log "\033[1;32m✅ Массив действительно деградирован и содержит одно устройство — всё верно.\033[0m"
     else
-        log -e "\033[1;31m❌ Состояние массива не соответствует ожидаемому (degraded, 1 устройство).\033[0m"
+        log "\033[1;31m❌ Состояние массива не соответствует ожидаемому (degraded, 1 устройство).\033[0m"
         exit 1
     fi
 
     if [ ! -f "$CONFIG_FILE" ]; then
-        log -e "\033[1;31m❌ Файл конфигурации не найден.\033[0m"
+        log "\033[1;31m❌ Файл конфигурации не найден.\033[0m"
         exit 1
     fi
 
@@ -369,65 +369,65 @@ step_two() {
     source "$CONFIG_FILE"
 
     if [[ -z "$PARENT_DISK" || -z "$SECOND_DISK" || -z "$PART_NUMBER" ]]; then
-        log -e "\033[1;31m❌ Не удалось загрузить данные из конфигурационного файла.\033[0m"
+        log "\033[1;31m❌ Не удалось загрузить данные из конфигурационного файла.\033[0m"
         exit 1
     fi
 
-    log -e "\033[1;32m✅ Данные из конфигурационного файла успешно загружены.\033[0m"
+    log "\033[1;32m✅ Данные из конфигурационного файла успешно загружены.\033[0m"
 
-    log -e "\033[1;37mОсновной диск: $PARENT_DISK\033[0m"
-    log -e "\033[1;37mВторой диск: $SECOND_DISK\033[0m"
-    log -e "\033[1;37mНомер диска в RAID: $PART_NUMBER\033[0m"
+    log "\033[1;37m[i] Основной диск: $PARENT_DISK\033[0m"
+    log "\033[1;37m[i] Второй диск: $SECOND_DISK\033[0m"
+    log "\033[1;37m[i] Номер диска в RAID: $PART_NUMBER\033[0m"
 
-    log -e "\033[1;37mВыполняем миграцию системных и загрузочных разделов посекторно...\033[0m"
+    log "\033[1;37m[i] Выполняем миграцию системных и загрузочных разделов посекторно...\033[0m"
 
     if dd if=${PARENT_DISK}1 of=${SECOND_DISK}1 >/dev/null 2>&1; then
-        log -e "\033[1;32m✅ Миграция первого раздела успешно выполнена.\033[0m"
+        log "\033[1;32m✅ Миграция первого раздела успешно выполнена.\033[0m"
     else
-        log -e "\033[1;31m❌ Не удалось выполнить миграцию первого раздела.\033[0m"
+        log "\033[1;31m❌ Не удалось выполнить миграцию первого раздела.\033[0m"
         exit 1
     fi
 
     if dd if=${PARENT_DISK}2 of=${SECOND_DISK}2 >/dev/null 2>&1; then
-        log -e "\033[1;32m✅ Миграция второго раздела успешно выполнена.\033[0m"
+        log "\033[1;32m✅ Миграция второго раздела успешно выполнена.\033[0m"
     else
-        log -e "\033[1;31m❌ Не удалось выполнить миграцию второго раздела.\033[0m"
+        log "\033[1;31m❌ Не удалось выполнить миграцию второго раздела.\033[0m"
         exit 1
     fi
 
-    log -e "\033[1;32m✅ Миграция системных и загрузочных разделов успешно выполнена.\033[0m"
+    log "\033[1;32m✅ Миграция системных и загрузочных разделов успешно выполнена.\033[0m"
     
-    log -e "\033[1;37mМонтирование загрузочного раздела...\033[0m"
+    log "\033[1;37m[i] Монтирование загрузочного раздела...\033[0m"
 
     if mount ${SECOND_DISK}2 /mnt >/dev/null 2>&1; then
-        log -e "\033[1;32m✅ Загрузочный раздел успешно монтирован.\033[0m"
+        log "\033[1;32m✅ Загрузочный раздел успешно монтирован.\033[0m"
     else
-        log -e "\033[1;31m❌ Не удалось монтировать загрузочный раздел.\033[0m"
+        log "\033[1;31m❌ Не удалось монтировать загрузочный раздел.\033[0m"
         exit 1
     fi
 
-    log -e "\033[1;37mРегистрация и установка GRUB в монтированный раздел с учетом RAID...\033[0m"
+    log "\033[1;37m[i] Регистрация и установка GRUB в монтированный раздел с учетом RAID...\033[0m"
 
     if grub-install --boot-directory /mnt ${SECOND_DISK} >/dev/null 2>&1; then
-        log -e "\033[1;32m✅ GRUB успешно установлен в монтированный раздел.\033[0m"
+        log "\033[1;32m✅ GRUB успешно установлен в монтированный раздел.\033[0m"
     else
-        log -e "\033[1;31m❌ Не удалось установить GRUB в монтированный раздел.\033[0m"
+        log "\033[1;31m❌ Не удалось установить GRUB в монтированный раздел.\033[0m"
         exit 1
     fi
 
     if umount ${SECOND_DISK}2 >/dev/null 2>&1; then
-        log -e "\033[1;32m✅ Загрузочный раздел успешно демонтирован.\033[0m"
+        log "\033[1;32m✅ Загрузочный раздел успешно демонтирован.\033[0m"
     else
-        log -e "\033[1;31m❌ Не удалось демонтировать загрузочный раздел.\033[0m"
+        log "\033[1;31m❌ Не удалось демонтировать загрузочный раздел.\033[0m"
         exit 1
     fi
 
-    log -e "\033[1;37mВосстановление функционала RAID-массива...\033[0m"
+    log "\033[1;37m[i] Восстановление функционала RAID-массива...\033[0m"
 
     if mdadm /dev/md0 --add-spare ${PARENT_DISK}${PART_NUMBER} >/dev/null 2>&1; then
-        log -e "\033[1;37m✅ RAID-массив успешно восстановлен.\033[0m"
+        log "\033[1;37m✅ RAID-массив успешно восстановлен.\033[0m"
     else
-        log -e "\033[1;31m❌ Не удалось восстановить RAID-массив.\033[0m"
+        log "\033[1;31m❌ Не удалось восстановить RAID-массив.\033[0m"
         exit 1
     fi
 
@@ -435,30 +435,30 @@ step_two() {
     consistency_policy=$(echo "$STATUS_CHECKING" | awk -F': ' '/Consistency Policy/ {print $2}' | xargs)
     raid_state=$(echo "$STATUS_CHECKING" | awk -F': ' '/State/ {print $2}' | xargs)
 
-    log -e "\033[1;37mСостояние RAID: $raid_state\033[0m"
-    log -e "\033[1;37mПолитика согласованности: $consistency_policy\033[0m"
+    log "\033[1;37m[i] Состояние RAID: $raid_state\033[0m"
+    log "\033[1;37m[i] Политика согласованности: $consistency_policy\033[0m"
 
     # Проверка состояния
-    [[ "$raid_state" == *degraded* ]] && log -e "\033[1;32m✅ RAID в состоянии деградации.\033[0m" || log -e "\033[1;31m❌ RAID не деградирован.\033[0m"
-    [[ "$raid_state" == *clean* ]]    && log -e "\033[1;32m✅ RAID в состоянии чистоты (clean).\033[0m" || log -e "\033[1;31m❌ RAID не в состоянии clean.\033[0m"
-    [[ "$raid_state" == *recovering* ]] && log -e "\033[1;32m✅ RAID восстанавливается (recovering).\033[0m" || log -e "\033[1;33m⚠️ RAID пока не восстанавливается.\033[0m"
+    [[ "$raid_state" == *degraded* ]] && log "\033[1;32m✅ RAID в состоянии деградации.\033[0m" || log "\033[1;31m❌ RAID не деградирован.\033[0m"
+    [[ "$raid_state" == *clean* ]]    && log "\033[1;32m✅ RAID в состоянии чистоты (clean).\033[0m" || log "\033[1;31m❌ RAID не в состоянии clean.\033[0m"
+    [[ "$raid_state" == *recovering* ]] && log "\033[1;32m✅ RAID восстанавливается (recovering).\033[0m" || log "\033[1;33m⚠️ RAID пока не восстанавливается.\033[0m"
 
     # Проверка политики согласованности
-    [[ "$consistency_policy" == *resync* ]] && log -e "\033[1;32m✅ RAID синхронизируется (resync).\033[0m" || log -e "\033[1;31m❌ RAID не в процессе resync.\033[0m"
+    [[ "$consistency_policy" == *resync* ]] && log "\033[1;32m✅ RAID синхронизируется (resync).\033[0m" || log "\033[1;31m❌ RAID не в процессе resync.\033[0m"
 
     # Можно добавить проверку, что degraded + clean = норм для текущего этапа
     if [[ "$raid_state" == *degraded* && "$raid_state" == *clean* ]]; then
-        log -e "\033[1;32m✅ RAID готов к восстановлению (degraded + clean).\033[0m"
+        log "\033[1;32m✅ RAID готов к восстановлению (degraded + clean).\033[0m"
     else
-        log -e "\033[1;31m❌ RAID не в ожидаемом состоянии для восстановления.\033[0m"
+        log "\033[1;31m❌ RAID не в ожидаемом состоянии для восстановления.\033[0m"
         exit 1
     fi
 
-    log -e "\033[1;37mВосстановление функционала RAID-массива завершено.\033[0m"
+    log "\033[1;37m[i] Восстановление функционала RAID-массива завершено.\033[0m"
 
-    log -e "\033[1;32m✅ Все этапы завершены.\033[0m"
+    log "\033[1;32m✅ Все этапы завершены.\033[0m"
 
-    log -e "\033[1;37mСкрипт автоматически уберет себя из автозагрузки.\033[0m"
+    log "\033[1;37m[i] Скрипт автоматически уберет себя из автозагрузки.\033[0m"
 
     service_unregistry
 
@@ -467,11 +467,11 @@ step_two() {
 
 case "$1" in
     --start)
-        echo "Выберите этап конфигурации:"
-        echo "1. Доперезагрузочная реализация"
-        echo "2. Послезагрузочная реализация"
+        echo -e "\033[1;37m[i] Выберите этап конфигурации:\033[0m"
+        echo -e "\033[1;37m1. Доперезагрузочная реализация\033[0m"
+        echo -e "\033[1;37m2. Послезагрузочная реализация\033[0m"
 
-        read -p "Введите номер этапа: " STEP
+        read -p "[r] Введите номер этапа: " STEP
 
         case "$STEP" in
             1)
@@ -481,19 +481,19 @@ case "$1" in
             step_two
             ;;
             *)
-            echo -e "\033[1;37mНеверный номер этапа: $STEP\033[0m" 1>&2
+            echo -e "\033[1;31m❌ Неверный номер этапа: $STEP\033[0m" 1>&2
             exit 1
             ;;
         esac
         ;;
     --help)
-        echo "Использование raid-configuration:"
-        echo "  --auto - Автоматический процесс конфигурации"
-        echo "  --start - Запустить процесс полностью"
-        echo "  --step [1/2] - Запустить процесс конкретного этапа"
-        echo "  --help - Показать справку"
-        echo "  --get-vg - Получить главный LVM Volume Group"
-        echo "  --daemon-env - Автозапуск второго этапа конфигурации"
+        echo -e "\033[1;37m[i] Использование raid-configuration:\033[0m"
+        echo -e"\033[1;37m  --auto - Автоматический процесс конфигурации\033[0m"
+        echo -e"\033[1;37m  --start - Запустить процесс полностью\033[0m"
+        echo -e"\033[1;37m  --step [1/2] - Запустить процесс конкретного этапа\033[0m"
+        echo -e"\033[1;37m  --help - Показать справку\033[0m"
+        echo -e"\033[1;37m  --get-vg - Получить главный LVM Volume Group\033[0m"
+        echo -e"\033[1;37m  --daemon-env - Автозапуск второго этапа конфигурации\033[0m"
         ;;
     --auto)
         step_one
@@ -507,21 +507,21 @@ case "$1" in
             step_two
             ;;
             *)
-            echo -e "\033[1;37mНеверный номер этапа: $2\033[0m" 1>&2
+            echo -e "\033[1;31m❌ Неверный номер этапа: $2\033[0m" 1>&2
             exit 1
             ;;
         esac
         ;;
     --get-vg)
         MAIN_LVM_VGID=$(lsblk -o NAME -n -r | grep -oP 'VG\K[0-9]+(?=-lv_)' | sort -u)
-        echo -e "\033[1;37mГлавный LVM Volume Group: $MAIN_LVM_VGID\033[0m"
+        echo -e "\033[1;37m[i] Главный LVM Volume Group: $MAIN_LVM_VGID\033[0m"
         exit 0
         ;;
     --daemon-env)
         step_two
         ;;
     *)
-        echo -e "\033[1;37mНеверная опция: $1. Используйте $0 --help\033[0m" 1>&2
+        echo -e "\033[1;31m❌ Неверная опция: $1. Используйте $0 --help\033[0m" 1>&2
         exit 1
         ;;
 esac
